### ISSUE TITLE
keycloak setup problem

### ISSUE THREAD

**Issue by G-Akiraka** [GramThanos/vpn-oidc#3] opened 2022-03-24 08:18 UTC
How to configure after keycloak Add Client? I add redirect url address to vpn.xxx.com, set the access type to confidential, and then set credentials. But if fails when running auto.py. The password of the code is environment variable, and what code should I fill in?

**Comment by GramThanos** [comment] 2022-03-24 09:35
This sounds like a duplicate of #2.

Inside your server auth.py you just add the OIDC info (endpoints, clientid and secret). The password code is given by the OpenVPN server, it will call the auth.py script automatically upon a user's request for authentication. (You have to configure the script to run as an alternative authentication method on the OpenVPN configuration).

**Comment by G-Akiraka** [comment] 2022-03-24 15:35
Thank you, the issue has been resolved.
1. How to solve the client redirection address? It seems that a corresponding service needs to be set up for the client to log in to redirect.
2. The client fails to obtain data when running the asynchronous request method, and the modification method has been resolved.
3. / client/app/preload. Js line 190 remote access pointer null pointer and 191 and unconstrained style, code no longer continue execution, unable to see the following page.

**Comment by GramThanos** [comment] 2022-03-24 20:18
I am not sure what you are asking, but I can explain a bit how the redirect works.

On OIDC you have website A asking for the identity of website B. In our case we don't have a website, we have a VPN service.

In OIDC the user starts from website A, is redirected to website B and then after authentication he is redirected back to website A (redirect address) posts the data to A and the backend of A contacts the B (using a secret) to verify the action and get the actual identity.

In our case we dont have a website, thus, our VPN client opens a page directly to B and waits B to redirect the user to a website and interrupts the redirect to get the returned info.

For security reasons, you should own the redirect domain but theoretically you dont need it.

The OIDC service needs to know this redirect url, or at least be able to validate if the given one is correct (e.g. using a regexp or by having a fixed redirect url)

**Comment by GramThanos** [comment] 2022-03-24 20:20
these info can be configured on the config.json of the client and the same info should be configured on the OIDC server.

**Comment by G-Akiraka** [comment] 2022-03-25 00:19
Thanks, I used go to rewrite a post request to implement odic authentication, and the test works fine

**Closed** 2022-03-25 18:04 UTC

**Comment by CharkeyQK** [comment] 2023-05-30 01:41
@G-Akiraka 方便联系吗，关于这个项目有些问题想请教下你？
